# Quartz config file
app:
  log:
    enabled: true
    trap: false

# Engine settings
engine:
  # Projects pathes for components searchig like files, payloads etc
  projects:
  - ./
  - ../default
  # default arguments
  default:
    # For undefined route will be use followng route
    route-name: make
